name: Maxyerli
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  yayin:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      contents: write
    steps:
    - name: 📥 Depoyu klonla
      uses: actions/checkout@v4
      
    - name: 🐍 Python kurulumu
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: 📦 FFmpeg ve Kurulumlar
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends ffmpeg ca-certificates openssl
        pip install requests

    - name: 📥 Kayıtlı State Dosyasını İndir
      continue-on-error: true
      run: |
        curl -sL https://github.com/${{ github.repository }}/releases/download/state-data/state_yerli.json -o state_yerli.json

    - name: 🚀 Yayını başlat
      env:
        STATE_FILE_NAME: "state_yerli.json"
      run: python -u yerli2.py

    - name: 💾 Son Durumu Release Üzerinde Güncelle
      if: always()
      uses: softprops/action-gh-release@v1
      with:
        files: state_yerli.json
        tag_name: state-data
        name: "Yayın Kaldığı Yer (State)"
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: 🔁 6 Saat Süre Dolunca Otomatik Yeni Run Tetikle
      if: failure() || success()
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        curl -X POST \
          -H "Authorization: token $GH_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          "https://api.github.com/repos/${{ github.repository }}/actions/workflows/yerli2.yml/dispatches" \
          -d '{"ref":"${{ github.ref_name }}"}'


https://s9.gelsistirire.top:443/d/yinlcacpsk3rtzj5b3wr5rovdjxiqdsk5n53tonobvq6yvwlbr2sr6zfh2jvxws62p3zi4re/Hukumet%20Kadin%202013%20WEB%20DL%201080p%20trdub.mp4

Bu linki yayında oynatmıyor neden acaba ve bu sorun nasıl çözebilirim
